---
version: '3.5'

services:
  zabbix-postgres:
    container_name: zabbix-postgres
    image: postgres:alpine
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      PGDATA: /data/zabbix-postgres
    volumes:
       - zabbix-postgres:/data/zabbix-postgres
    ports:
      - "195.2.85.41:5432:5432"
    networks:
      - zabbix-network
    restart: unless-stopped

  zabbix-server:
    container_name: zabbix-server 
    image: zabbix/zabbix-server-pgsql:alpine-latest
    environment:
      DB_SERVER_HOST: zabbix-postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
    volumes:
       - zabbix-server:/data/zabbix-server
    ports:
      - "195.2.85.41:10051:10051"
    networks:
      - zabbix-network
    restart: unless-stopped

  zabbix-web:
    container_name: zabbix-web
    image: zabbix/zabbix-web-nginx-pgsql:alpine-latest
    environment:
      DB_SERVER_HOST: zabbix-postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: Europe/Moscow
    volumes:
       - zabbix-web:/data/zabbix-web
    ports:
      - "195.2.85.41:80:8080"
      - ""
    networks:
      - zabbix-network
    restart: unless-stopped


networks:
  zabbix-network:
    driver: bridge

volumes:
    zabbix-postgres:
    zabbix-server:
    zabbix-web:
